"""add language field to messages and comments

Revision ID: a5b105bfbc3d
Revises: b7f9783df6ed
Create Date: 2025-08-10 16:25:23.952118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b105bfbc3d'
down_revision = 'b7f9783df6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
